<?php
use Illuminate\Database\Seeder;
class PoliteknikTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array('Politeknik Manufaktur Bandung',
            'Politeknik Negeri Jakarta',
            'Politeknik Negeri Medan',
            'Politeknik Negeri Bandung',
            'Politeknik Negeri Semarang',
            'Politeknik Negeri Sriwijaya',
            'Politeknik Negeri Lampung',
            'Politeknik Negeri Ambon',
            'Politeknik Negeri Padang',
            'Politeknik Negeri Bali',
            'Politeknik Negeri Pontianak',
            'Politeknik Negeri Ujung Pandang',
            'Politeknik Negeri Manado',
            'Politeknik Perkapalan Negeri Surabaya',
            'Politeknik Negeri Banjarmasin',
            'Politeknik Negeri Lhokseumawe',
            'Politeknik Negeri Kupang',
            'Politeknik Elektronik Negeri Surabaya',
            'Politeknik Negeri Jember',
            'Politeknik Pertanian Negeri Pangkajene Kepulauan',
            'Politeknik Pertanian Negeri Kupang',
            'Politeknik Perikanan Negeri Tual',
            'Politeknik Negeri Malang',
            'Politeknik Pertanian Negeri Samarinda',
            'Politeknik Pertanian Negeri Payakumbuh',
            'Politeknik Negeri Samarinda',
            'Politeknik Negeri Media Kreatif',
            'Politeknik Manufaktur Negeri Bangka Belitung',
            'Politeknik Negeri Batam',
            'Politeknik Negeri Nusa Utara',
            'Politeknik Negeri Bengkalis',
            'Politeknik Negeri Balikpapan',
            'Politeknik Negeri Madura',
            'Politeknik Maritim Negeri Indonesia',
            'Politeknik Negeri Banyuwangi',
            'Politeknik Negeri Madiun',
            'Politeknik Negeri Fakfak',
            'Politeknik Negeri Sambas',
            'Politeknik Negeri Tanah Laut',
            'Politeknik Negeri Subang',
            'Politeknik Negeri Ketapang',
            'Politeknik Negeri Cilacap',
            'Politeknik Negeri Indramayu',
            'Politeknik Unggul LP3M',
            'Politeknik Ganesha',
            'Politeknik Mandiri Bina Prestasi',
            'Politeknik Profesional Mandiri',
            'Politeknik Poliprofesi Medan',
            'Politeknik LP3I Medan',
            'Politeknik Tugu 45 Medan',
            'Politeknik Santo Thomas',
            'Politeknik Trijaya Krama',
            'Politeknik Yanada',
            'Politeknik Tanjungbalai',
            'Politeknik Kesehatan YRSU Dr Rusdi',
            'Politeknik IT&B Medan',
            'Politeknik Bisnis Indonesia',
            'Politeknik Gihon',
            'Politeknik Wilmar Bisnis Indonesia',
            'Politeknik Akamigas Palembang',
            'Politeknik Anika Palembang',
            'Politeknik Darusalam',
            'Politeknik Sekayu',
            'Politeknik YPPB Belitang',
            'Politeknik Raflesia',
            'Politeknik Gajah Sakti',
            'Politeknik Muara Dua',
            'Politeknik Palcomtech',
            'Politeknik Darma Ganesha',
            'Politeknik Manufaktur Astra',
            'Politeknik Swadharma',
            'Politeknik Bunda Kandung',
            'Politeknik Tugu Jakarta',
            'Politeknik LP3I Jakarta',
            'Politeknik Global Indonesia',
            'Politeknik Karya Husada',
            'Politeknik Soca',
            'Politeknik Bina Budaya Cipta',
            'Politeknik Kelapa Sawit Citra Widya Edukasi',
            'Politeknik Kent',
            'Politeknik Piksi Input Serang',
            'Politeknik TEDC',
            'Politeknik Agroindustri',
            'Politeknik Al-Islam Bandung',
            'Politeknik Enjinering Indorama',
            'Politeknik Gajah Tunggal',
            'Politeknik Geologi Dan Pertambangan Agp',
            'Politeknik Gunakarya Indonesia Bekasi',
            'Politeknik Kesehatan Bhakti Pertiwi Husada',
            'Politeknik Kesehatan TNI-AU Ciumbuleuit',
            'Politeknik Komputer Niaga LPKIA',
            'Politeknik Krakatau',
            'Politeknik Kridatama Bandung',
            'Politeknik LP3I Bandung',
            'Politeknik Meta Industri Cikarang',
            'Politeknik Mitra Kusuma',
            'Politeknik Pajajaran Insan Cinta Bangsa Bandung',
            'Politeknik Perdana Mandiri',
            'Politeknik PGRI Banten',
            'Politeknik Piksi Ganesha',
            'Politeknik Pos Indonesia',
            'Politeknik Praktisi Bandung',
            'Politeknik Sukabumi',
            'Politeknik Tri Mitra Karya Mandiri',
            'Politeknik Triguna Tasikmalaya',
            'Politeknik Tunas Pemuda',
            'Politeknik Mekatronika Sanata Dharma',
            'Politeknik Muhammadiyah Yogyakarta',
            'Politeknik API Yogyakarta',
            'Politeknik LPP Yogyakarta',
            'Politeknik Seni Yogyakarta',
            'Politeknik Kesehatan Bhakti Setya Indonesia',
            'Politeknik Kesehatan Permata Indonesia Yogyakarta',
            'Politeknik Harapan Bersama',
            'Politeknik Sawunggalih Aji',
            'Politeknik Pratama Mulia',
            'Politeknik Muhammadiyah Magelang',
            'Politeknik Pratama',
            'Politeknik Ma arif',
            'Politeknik Dharma Patria',
            'Politeknik Indonusa Surakarta',
            'Politeknik Pusmanu',
            'Politeknik Purbaya',
            'Politeknik Unggulan Sragen',
            'Politeknik Manufaktur Ceper',
            'Politeknik Stibisnis',
            'Politeknik Muhammadiyah Pekalongan',
            'Politeknik Banjarnegara',
            'Politeknik Muhammadiyah Tegal',
            'Politeknik Kesehatan Bhakti Mulia',
            'Politeknik ATMI',
            'Politeknik Trisila Dharma',
            'Politeknik Baja Tegal',
            'Politeknik Mitra Karya Mandiri',
            'Politeknik Santo Paulus Surakarta',
            'Politeknik Bina Trada Semarang',
            'Politeknik Kesehatan RS Dr Soepraoen Kesdam V',
            'Politeknik Kota Malang',
            'Politeknik NSC Surabaya',
            'Politeknik Ubaya',
            'Politeknik Unisma Malang',
            'Politeknik Cahaya Surya',
            'Politeknik Surabaya',
            'Politeknik Kesehatan Majapahit',
            'Politeknik Sakti Surabaya',
            'Politeknik Kediri',
            'Politeknik 17 Agustus 1945 Surabaya',
            'Politeknik Pertanian dan Peternakan Mapena',
            'Politeknik Nasional Denpasar',
            'Politeknik St Wilhelmus',
            'Politeknik Ganesa Guru',
            'Politeknik Widya Dharma Bali',
            'Politeknik Medica Farma Husada Mataram',
            'Politeknik Informatika Nasional',
            'Politeknik Gorontalo',
            'Politeknik Palu',
            'Politeknik Indotec Kendari',
            'Politeknik Bosowa',
            'Politeknik Caltex',
            'Politeknik Jambi',
            'Politeknik Kesehatan Siteba',
            'Politeknik Kampar',
            'Politeknik Pariwisata Batam',
            'Politeknik Hasnur',
            'Politeknik Muara Teweh',
            'Politeknik Tonggak Equator',
            'Politeknik Putra Bangsa Pontianak',
            'Politeknik Kotabaru',
            'Politeknik Sendawar',
            'Politeknik Malinau',
            'Politeknik Islam Syekh Salman Al-Farisi Rantau',
            'Politeknik Tanah Laut',
            'Politeknik Bisnis Lamda',
            'Politeknik Ilmu Pelayaran Balikpapan',
            'Politeknik Unggulan Kalimantan',
            'Politeknik Batulicin',
            'Politeknik Perdamaian Halmahera',
            'Politeknik Sains & Teknologi Wiratama Maluku Utara',
            'Politeknik Halmahera',
            'Politeknik Aceh',
            'Politeknik Aceh Selatan',
            'Politeknik Indonesia Venezuela',
            'Politeknik Amamapare',
            'Politeknik Katolik Saint Paul',
            'Politeknik Pertanian Yasanto',
            'Politeknik Teknologi Kimia Industri',
            'Politeknik Informatika Del Toba Samosir',
            'Politeknik Ganesha Medan',
            'Politeknik Kemenkes Medan',
            'Politeknik ATI Padang',
            'Politeknik Kemenkes Padang',
            'Poltekkes Palembang',
            'Politeknik Kemenkes Riau',
            'Poltekkes Tanjung Karang',
            'Poltekkes Pangkal Pinang',
            'Poltekkes Kemenkes Banten',
            'Poltekkes Kemenkes Jakarta',
            'Politeknik Kesehatan Yapkesbi Sukabumi',
            'Poltekkes Kemenkes Bandung',
            'Poltekkes Kemenkes Tasikmalaya',
            'Poltekkes Kemenkes Semarang',
            'Poltekkes Kemenkes Yogyakarta',
            'Poltekkes Kemenkes Surakarta',
            'Poltekkes Kemenkes Malang',
            'Poltekkes Kemenkes Surabaya',
            'Poltekkes Kemenkes Kupang',
            'Poltekkes Kemenkes Pontianak',
            'Poltekkes Kemenkes Banjarmasin',
            'Poltekkes Kemenkes Palangkaraya',
            'Poltekkes Kemenkes Samarinda',
            'Poltekkes Kemenkes Mamuju',
            'Poltekkes Kemenkes Makassar',
            'Poltekkes Kemenkes Kendari',
            'Poltekkes Kemenkes Palu',
            'Poltekkes Kemenkes Gorontalo',
            'Poltekkes Kemenkes Manado',
            'Poltekkes Kemenkes Maluku',
            'Poltekkes Kemenkes Ternate',
            'Poltekkes Kemenkes Jayapura',
            'Poltekkes Kemenkes Sorong',
            'Politeknik Kelautan dan Perikanan Belitung',
            'Politeknik Maritim AMI Makassar',
            'Politeknik Ilmu Pelayaran Makassar',
            'Politeknik ATI Makassar',
            'Politeknik Hasnur Banjarmasin',
            'Poltekkes Kemenkes Denpasar',
            'Poltekkes Kemenkes Mataram',
            'Politeknik Ilmu Pelayaran Surabaya',
            'Politeknik Kelautan dan Perikanan Sidoarjo',
            'Politeknik ATK Yogyakarta',
            'Politeknik STTT Bandung',
            'Politeknik AKA Bogor',
            'Politeknik IPDN Bandung',
            'Politeknik STMI Jakarta',
            'Politeknik APP Jakarta',
            );

        foreach($data as $item)
        {
            $result = DB::table('politeknik')->insert([
                'politeknik' => $item,
            ]);
        }
    }
}